name: Deploy to Azure Container Apps
on:
    workflow_dispatch:
    workflow_run:
        workflows: ['Docker build and publish to GHCR']
        types:
            - completed

env:
    AZURE_RESOURCE_GROUP: sample-rg
    AZURE_LOCATION: west europe
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: sample-db

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            # checkout the repo
            - name: 'Checkout GitHub Action'
              uses: actions/checkout@main

            - name: 'Login via Azure CLI'
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: 'Deploy PostgreSQL to Azure Container Instances'
              uses: 'azure/aci-deploy@v1'
              with:
                  resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
                  dns-name-label: sample-db
                  image: postgres:latest
                  name: sample-db
                  location: ${{ env.AZURE_LOCATION }}
                  ports: '5432'
                  environment-variables: |
                      'POSTGRES_USER=${{ env.POSTGRES_USER }},POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }},POSTGRES_DB=${{ env.POSTGRES_DB }}'

            - name: 'Deploy server to Azure Container Instances'
              uses: 'azure/aci-deploy@v1'
              with:
                  resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
                  dns-name-label: sample-server
                  image: ghcr.io/${{ github.repository_owner }}/sample-server:latest
                  registry-username: ${{ github.repository_owner }}
                  registry-password: ${{ secrets.GH_TOKEN }}
                  name: sample-server
                  location: ${{ env.AZURE_LOCATION }}
                  ports: '8080'
                  environment-variables: |
                      'PORT=8080,DB_HOST=${{ env.POSTGRES_DB }},DB_PORT=5432,DB_USER=${{ env.POSTGRES_USER }},DB_PASSWORD=${{ env.POSTGRES_PASSWORD }},DB_NAME=${{ env.POSTGRES_DB }}'

            - name: 'Deploy client to Azure Container Instances'
              uses: 'azure/aci-deploy@v1'
              with:
                  resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
                  dns-name-label: sample-client
                  image: ghcr.io/${{ github.repository_owner }}/sample-client:latest
                  registry-username: ${{ github.repository_owner }}
                  registry-password: ${{ secrets.GH_TOKEN }}
                  name: sample-client
                  location: ${{ env.AZURE_LOCATION }}
                  ports: '80'
                  environment-variables: ''
