name: Deploy to Azure Container Apps
on:
    workflow_dispatch:
    workflow_run:
        workflows: ['Docker build and publish to GHCR']
        types:
            - completed

env:
    AZURE_RESOURCE_GROUP: 'sample-rg'
    AZURE_LOCATION: 'westeurope'
    POSTGRES_HOST_NAME: 'sample-db-v2rga'
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'postgres'
    POSTGRES_DB: 'sampleDB'

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            # checkout the repo
            - name: 'Checkout GitHub Action'
              uses: actions/checkout@main

            - name: 'Login via Azure CLI'
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Create Resource Group if not exist
              uses: azure/CLI@v2
              with:
                  inlineScript: |
                      if [ $(az group exists --name ${{ env.AZURE_RESOURCE_GROUP }}) = false ]; then
                        az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location ${{ env.AZURE_LOCATION }}
                      fi

            - name: Create Postgres if not exist
              uses: azure/CLI@v2
              with:
                  inlineScript: |
                      if ! az postgres flexible-server show --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.POSTGRES_HOST_NAME }} &>/dev/null; then
                        az postgres flexible-server create \
                          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
                          --name ${{ env.POSTGRES_HOST_NAME }} \
                          --location ${{ env.AZURE_LOCATION }} \
                          --admin-user ${{ env.POSTGRES_USER }} \
                          --admin-password ${{ env.POSTGRES_PASSWORD }} \
                          --tier Burstable \
                          --sku-name Standard_B1ms \
                          --storage-size 32 \
                          --version 14 \
                          --public-access 0.0.0.0 \
                          --high-availability Disabled \
                          --yes
                      fi

            - name: 'Deploy server to Azure Container Instances'
              uses: 'azure/aci-deploy@v1'
              with:
                  resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
                  dns-name-label: sampleserver
                  image: ghcr.io/ghornon/sample-server:latest
                  registry-username: ${{ github.repository_owner }}
                  registry-password: ${{ secrets.GH_TOKEN }}
                  name: sample-server
                  location: ${{ env.AZURE_LOCATION }}
                  ports: '8080'
                  environment-variables: |
                      PORT=8080,DB_HOST=${{ env.POSTGRES_HOST_NAME }}.postgres.database.azure.com,DB_PORT=5432,DB_USER=${{ env.POSTGRES_USER }},DB_PASSWORD=${{ env.POSTGRES_PASSWORD }},DB_NAME=${{ env.POSTGRES_DB }}

            - name: 'Deploy client to Azure Container Instances'
              uses: 'azure/aci-deploy@v1'
              with:
                  resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
                  dns-name-label: sampleclient
                  image: ghcr.io/ghornon/sample-client:latest
                  registry-username: ${{ github.repository_owner }}
                  registry-password: ${{ secrets.GH_TOKEN }}
                  name: sample-client
                  location: ${{ env.AZURE_LOCATION }}
                  ports: '80'
